version: '3.8'

services:
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  create-topic:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    volumes:
      - ./create-topic.sh:/create-topic.sh
    command: ["bash", "/create-topic.sh"]

  react:
    image: 'olow/sw-react-app'
    ports:
      - '3000:3000'

  node:
    image: 'olow/sw-node-app'
    ports:
      - '3535:3535'
    depends_on:
      - go

  go:
    image: 'olow/sw-go-server'
    ports:
      - '8080:8080'
    depends_on:
      - kafka
      - create-topic